# Generated by Django 5.2.8 on 2025-11-12 14:16

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('overall_score', models.IntegerField(help_text='Overall fit score from 1-10')),
                ('detailed_analysis', models.JSONField(default=dict, help_text='Detailed breakdown including skill matches, strengths, weaknesses')),
                ('recommendation', models.CharField(choices=[('interview', 'Interview'), ('decline', 'Decline')], default='decline', max_length=20)),
                ('assessment_document', models.FileField(blank=True, null=True, upload_to='assessments/%Y/%m/%d/')),
                ('processing_logs', models.JSONField(default=list, help_text='Log of processing steps and decisions')),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=100)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(max_length=255)),
                ('profile_url', models.URLField()),
                ('repos_data', models.JSONField(default=dict, help_text='Cached repository data from GitHub API')),
                ('analysis', models.JSONField(default=dict, help_text='Computed metrics and analysis')),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('fetch_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GitHub Profile',
                'verbose_name_plural': 'GitHub Profiles',
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills for the position')),
                ('nice_to_have_skills', models.JSONField(default=list, help_text='Optional skills that are beneficial')),
                ('experience_years', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stage', models.CharField(help_text='Processing stage name (e.g., resume_parsing)', max_length=100)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context and data for this stage')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('parsing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='StakeholderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stakeholder_identifier', models.CharField(help_text='Telegram user ID or identifier', max_length=255)),
                ('stakeholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('comment', 'Comment')], max_length=20)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(max_length=255, unique=True)),
                ('telegram_chat_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Stakeholder Feedback',
                'verbose_name_plural': 'Stakeholder Feedback',
                'ordering': ['-created'],
            },
        ),
    ]
