# Generated by Django 5.2.8 on 2025-11-12 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobdescription'),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='recruitment.candidate'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_feedback', to='recruitment.evaluation'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['overall_score'], name='recruitment_overall_d702f3_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['recommendation'], name='recruitment_recomme_199ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='githubprofile',
            index=models.Index(fields=['username'], name='recruitment_usernam_8880bf_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='recruitment_email_9164c0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status'], name='recruitment_status_5d798c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['celery_task_id'], name='recruitment_celery__3e80e6_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['candidate', 'stage'], name='recruitment_candida_72dc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['status'], name='recruitment_status_293aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderfeedback',
            index=models.Index(fields=['telegram_message_id'], name='recruitment_telegra_5e0b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderfeedback',
            index=models.Index(fields=['stakeholder_identifier'], name='recruitment_stakeho_173f3f_idx'),
        ),
    ]
