# Generated by Django 5.2.8 on 2025-11-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the resume file for deduplication', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
